### ISSUE TITLE
`Ctrl + C` shortcut clears the session

### ISSUE THREAD

**Issue by micc83** [chevere/xr#42]
When `Ctrl + C` key shortcut is typed inside the browser it clears the session as the `C` key is mapped with "Clear Session".

**Comment by rodber** [comment]
Try with the referenced commit. It blocks meta _or_ ctrl _or_ alt for the keys used to control XR so it should ignore all the browser + os combinations.

**Comment by micc83** [comment]
Yep, it seems to work now on Chrome for Windows. Thank you.
