### ISSUE TITLE
Chevere\Trace\TraceDocument::__construct(): Argument #2 ($format) must be of type Chevere\Trace\Interfaces\TraceFormatInterface

### ISSUE THREAD

**Issue by AuroraYolo** [chevere/xr#49]
![image](https://user-images.githubusercontent.com/20986749/153531925-4b97d554-9bd2-4ca6-afda-12abb48fa123.png)

**Comment by rodber** [comment]
💡 Try to stick with the [tagged releases](https://github.com/chevere/xr/tags) as I'm still not delivering stable branches. I will start providing that from `0.2.X`.

The [patch](https://github.com/chevere/trace/issues/2) for the issue you previously reported will appear in XR for release [0.2.0](https://github.com/chevere/xr/milestone/4) (Egocentrico) ([0.2](https://github.com/chevere/xr/tree/0.2) branch).
