### ISSUE TITLE
Question: Does XR also work with Laravel?

### ISSUE THREAD

**Issue by slakbal** [chevere/xr#59]
Hi There, 

This looks really awesome, quick question will it also work with Laravel?

Thanks!

**Comment by rodber** [comment]
Hi @slakbal

XR Debug works in any PHP 8 codebase.

At this time it doesn't provide _extra_ support for Laravel or any other framework/cms (as tailored methods for these) but there's a layer for adding custom inspectors: https://xr-docs.chevere.org/developer/custom-inspectors.html

**Comment by davisngl** [comment]
I have nothing to add this and you can either delete or mark my comment as a spam,

but I really appreciate the work you have put in this. Spatie is lowering their standards with their package maintenance + overpricing glorified `dd` tool that's not even properly cross-compatible without bloat.

Give them run for their money!
