### ISSUE TITLE
Support PHP 8.2

### ISSUE THREAD

**Issue by rodber** [chevere/xr#72]

**Comment by michabbb** [comment]
@rodber please check:

https://github.com/chevere/xr/pull/76
https://github.com/chevere/var-dump/pull/10
https://github.com/chevere/chevere/pull/157

without these changes, the code is running but you get **DEPRECATED** warnings.

**Comment by rodber** [comment]
I'm not seeing any deprecations on my runs (8.2.3).

**Comment by michabbb** [comment]
pardon, i wasn´t on the latest version 🙈
