### ISSUE TITLE
XR doesn't exist in bin

### ISSUE THREAD

**Issue by oscarmorrison** [chevere/xr#77]
Installed using:
`composer require --dev chevere/xr`

(also tried without --dev)

it installs `psr7` in main deps (which I don't really want)

but nothing in the bin:

`ls vendor/bin`
![image](https://github.com/chevere/xr/assets/1651212/53627d06-be1a-4efe-b116-1df606093fb9)

`xr` command not found

**Comment by rodber** [comment]
You can provide the server by several ways, you are referring to the [dependency server](https://xr-docs.chevere.org/server/#dependency-server):

```sh
composer require --dev chevere/xr-server
```

And I wrongly believe that using `composer require --dev chevere/xr` (or without `--dev`) did included `chevere/xr-server`. I need to fix the docs.

> it installs psr7 in main deps (which I don't really want)

```sh
❯ composer why nyholm/psr7
chevere/chevere 2.0.6 requires nyholm/psr7 (^1.5)
```

The package `nyholm/psr7` is required by [Writer](https://chevere.org/library/writer.html), used here to handle dump message as a stream. I enjoy working with strings using streams for reasons, but feel free to contribute a stream-free implementation here and I will move `Writer` from the `chevere/chevere` package which will cause to drop the dependency here.

**Comment by oscarmorrison** [comment]
@rodber 


Thanks for the update. So to be clear I need to install xr and xr server?

I don't understand why it's getting added as a composer main req. It can be / should be a package requirement. And at very least added to dev reqs only

**Comment by rodber** [comment]
XR is a server side debugger, it needs a server and a client. This is the client package, the one you add in your project.

XR server is a dev requirement in this package, I've no intention on making it a main requirement. For the server you can pick among a dependency server, a source server and a docker server, suit your needs.
