### ISSUE TITLE
Make array collapsible

### ISSUE THREAD

**Issue by eznix86** [chevere/xr#87]
Amazing work!

But sometimes when you have a big object or array, you have to scroll a lot. It should be nice if it was collapsible.

**Comment by rodber** [comment]
I also authored the vardump component in charge of provide variable instrospection for xrdebug/php and there's an ongoing issue regarding this: https://github.com/chevere/var-dump/issues/5

**Comment by rodber** [comment]
xrDebug 2.0 supports this.
