### ISSUE TITLE
iconv(): Detected an illegal character in input string

### ISSUE THREAD

**Issue by eznix86** [chevere/xr#88]
when trying to do
```
  xr(debug_backtrace());
```
I get this error
`iconv(): Detected an illegal character in input string`

**Comment by eznix86** [comment]
Managed to hack it with `xr(json_decode(json_encode(debug_backtrace())));`

**Comment by rodber** [comment]
Thanks, this has been fixed in chevere/var-dump 1.0.4: https://github.com/chevere/var-dump/releases/tag/1.0.4
Simply run `composer update` and it should update the package with the fix.
